<?php
// /pasar todo al block
$quoteid = Mage::getSingleton('checkout/session')->getQuoteId();
$_code = $this->getMethodCode(); ?>
<img src="http://www.todopago.com.ar/sites/todopago.com.ar/files/pluginstarjeta.jpg" alt="imagen_todopago" />
<ul class="form-list" id="payment_form_<?php echo $_code; ?>"
	style="display: none;">
	
	<input type="hidden" id="quote" name='payment[quote]'
	value="<?php echo $quoteid ?>"></input>
	<p>Al continuar con la compra, estarás ingresando a un sitio seguro de Todo Pago</p>
</ul>
